# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               KeviLand
tagline:             'a beta website'
url:                 https://keviland.github.io/to
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Kevin Landreneau
  url:               https://facebook.com/alibiagent
  email:             alibiagent@gmx.co.uk

# Custom vars
version:             1.0.0
